# Generated by Django 5.1.7 on 2025-05-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='promocode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
